[wip] adding option to provide range for age
dandi/dandi-cli pull request #1101
Opened 2022-08-17 18:04 UTC by djarecka

Adding range to the option for age. Using an ISO8601 extension for intervals, i.e:
`<ISOduration>/<ISOduration>` - both limits known
`/<ISOduration>` or `<ISOduration>/` - one limit is  unknown
`/` - both limits are unknown

Please check the tests for the new examples that will be covered, closes #1090 

I've realized that there is some redundant code for the iso formatting (some in utils.py), will try to clean it a bit later

2022-08-17 18:26 UTC, jwodder requested changes

2022-08-17 18:26 UTC, jwodder commented on dandi/metadata.py
> +                    f"Age that use / for range need to use ISO8601 format, "
```suggestion
                    f"Ages that use / for range need to use ISO8601 format, "
```

2022-08-17 18:26 UTC, jwodder commented on dandi/metadata.py
> +            "and they should have a consistent units."
```suggestion
            "The upper limit has to be larger than the lower limit, "
            "and they should have consistent units."
```

2022-08-17 22:36 UTC, djarecka commented
@jwodder - i have some unrelated to my changes issues. I can fix spelling to please the linter, but there are also tests in `test_video_organize` that gives error under dev-deps. Do you know what is wrong?

2022-08-18 00:31 UTC, jwodder commented
@djarecka The dev-deps failures are known and are being dealt with in #1100; ignore them for now.  As for the linter, see if the error is still there after you address codespell's concerns.

2022-08-18 02:20 UTC, djarecka commented
codespell complains about name of the file and regex... 
https://github.com/dandi/dandi-cli/blob/master/dandi/tests/test_pynwb_utils.py#L43
will think about it

2022-08-18 16:54 UTC, yarikoptic commented
Thank you @djarecka and @jwodder ! Let's proceed!

2022-08-18 16:55 UTC, merged

2022-08-19 02:15 UTC, djarecka commented
@bendichter - it was merged sooner than I thought, so not sure if you had a chance to check the examples :)