Validation results refactoring: centralize results for different reused origins, use _pydantic_errors_to_validation_results more
dandi/dandi-cli pull request #1176
Opened 2022-12-16 18:11 UTC by yarikoptic

See individual commits messages for more information.

Please check (especially @TheChymera ) if my use of `_pydantic_errors_to_validation_results` is correct -- I am not sure any test is hitting that code path at all - can someone come up with a unittest to hit it?

2022-12-16 19:16 UTC, jwodder commented
@yarikoptic While you're messing with `_pydantic_errors_to_validation_results()`, could you please change the `Any` in the type signature to `Union`?  (The PR diff's nowhere the function definition, so I can't make this a code comment.)

2022-12-16 19:19 UTC, jwodder commented on dandi/files/bases.py
>      errors: Any[list[dict], Exception],
```suggestion
    errors: list[dict | Exception],
```

2022-12-16 19:23 UTC, jwodder requested changes
Shouldn't this PR be labelled "internal" instead of "patch"?  None of these changes appear to be externally visible.

2022-12-16 19:23 UTC, jwodder commented on dandi/files/bases.py
>      errors: Any[list[dict], Exception],
```suggestion
    errors: list[dict | Exception],
```

2022-12-16 19:23 UTC, jwodder commented on dandi/files/bases.py
> +                    e, str(self.filepath), dandiset_path=self.dandiset_path
```suggestion
                    [e], str(self.filepath), dandiset_path=self.dandiset_path
```

2022-12-17 09:06 UTC, TheChymera approved these changes
Looks good to me, the `partial()` definitions are pretty convenient. As for tests not hitting those two lines, I guess the “problem” is that nothing in our test suite is triggering those exceptions. This looks more like failsafe code, in case something that should never break by some coincidence does 🤔 not exactly sure how to make it break without breaking in other places before.

2022-12-19 14:02 UTC, yarikoptic commented
> Shouldn't this PR be labelled "internal" instead of "patch"? None of these changes appear to be externally visible.

my thinking was "because it changes visible to user results" due to " use _pydantic_errors_to_validation_results more". but indeed, I guess, could just be `internal`.

2022-12-19 14:08 UTC, yarikoptic commented
> This looks more like failsafe code, in case something that should never break by some coincidence does  not exactly sure how to make it break without breaking in other places before.

hm, shouldn't that `get_validation_errors` case be triggered on any asset with invalid according to pydantic model?  But let's continue on that in a separate issue

2023-07-07 22:21 UTC, yarikoptic commented
I think it might have been closed in error.  Should be redone.

2024-10-18 18:11 UTC, yarikoptic commented
too many conflicts and will be superseded by 
- https://github.com/dandi/dandi-cli/pull/1514

2024-10-18 18:11 UTC, closed without merging