Fail upload only for validation ERRORs and not necessarily WARNINGs or HINTs + log all errors
dandi/dandi-cli pull request #1186
Opened 2023-01-16 14:20 UTC by yarikoptic

Reported by a user in slack to be unable to upload a file, although validation did not report any errors.  Apparently we did not log errors and it was impossible to figure out what is going on.  So I have also added logging of those validation errors, without any custom serialization into a string so we log the most complete (and possibly the most useful since provides information on paths within file etc) representation.

2023-01-16 14:23 UTC, jwodder requested changes

2023-01-16 14:23 UTC, jwodder commented on dandi/upload.py
> +                                lgr.warning(" Error %d: %s", i + 1, e)
```suggestion
                            for i, e in enumerate(validation_errors, start=1):
                                lgr.warning(" Error %d: %s", i, e)
```

2023-01-16 20:44 UTC, yarikoptic commented
> Well this is an improvement but I'd really prefer if errors preventing upload were printed to the console as opposed to the logger. A user will want to find these every time they occur.

where should they be printed in this UI e.g. while uploading 100 files and each one of them having varying number of errors?

2023-01-16 21:16 UTC, yarikoptic commented
marking for release so we some users unblocked and also release that minor tune up for zarr files pagination.
If there would be no objections , I  will merge by the end of the work day.

2023-01-17 15:26 UTC, bendichter commented
> where should they be printed in this UI e.g. while uploading 100 files and each one of them having varying number of errors?

Well ideally we'd catch these errors on the nwbinspector step, which packages these errors into a report. If the user ignores those warnings, or if for some reason there is a misalignment between `nwbinspector`, `dandi validate`, and `dandi upload`, then yes, I would like to print out hundreds of lines of errors to the console.

2023-01-17 15:33 UTC, satra commented
@bendichter - i think what yarik is getting at is that currently the upload command reports progress, which is more useful to most users, and if there are errors they are logged and one can look at those even while uploading. these are not just validation errors, they could connection timeouts and other errors that are unrelated to validation.

one option that may be useful is to summarize the current errors either on an interruption (SIGINT) or at the end of upload to the console. going through the log file is non-trivial for most users at the moment to figure out what is happening, so a helper to summarize would be useful.

2023-01-17 16:15 UTC, yarikoptic commented
Thank you for the points -- I think they are worth discussion in dedicated issues - feel welcome to open new ones to improve UX. But we do need this PR to avoid failing uploads and do log errors -- that is complimentary to summaries or other dumps visible to the user IMHO, so I will proceed as is for now.

2023-01-17 16:15 UTC, merged