Add workflow for publishing model schemata to dandi/schema
dandi/dandi-cli pull request #276
Opened 2020-11-19 17:27 UTC by jwodder

Closes #273.

2020-11-19 18:02 UTC, yarikoptic requested changes
looks good and ok to merge after addressing few comments

2020-11-19 18:02 UTC, yarikoptic commented on .github/workflows/publish-schemata.yml
> +          then git commit -m "Publish model schemata as of dandi $(git -C ../dandi describe --tags)"
```suggestion
          then git commit -m "Publish model schemata as of dandi-cli $(git -C ../dandi describe --tags)"
```

2020-11-19 18:04 UTC, jwodder commented on .github/workflows/publish-schemata.yml
> +      - dandi/model_types.py
Done.

2020-11-23 17:36 UTC, yarikoptic commented
Let's proceed!  Thank you @jwodder !

2020-11-23 17:36 UTC, merged