Tee all logs to user log directory
dandi/dandi-cli pull request #318
Opened 2020-12-14 21:10 UTC by jwodder

Closes #316 

Unfortunately, if the program exits abnormally, the final message giving the location of the logfile won't be printed.  I'm not aware of a way around this.

2020-12-15 00:15 UTC, yarikoptic requested changes
minor wish: uniform formatting within the log, so initial entries should also follow the format

2020-12-15 14:06 UTC, jwodder commented on dandi/cli/command.py
> +        print("os.getcwd() =", os.getcwd(), file=fp)
Done (kind of kludgily).

2020-12-15 14:11 UTC, jwodder commented
@yarikoptic I've figured out a way to ensure that the log file path is always printed, even on error.

2020-12-16 17:34 UTC, yarikoptic commented on dandi/cli/command.py
> +        print("os.getcwd() =", os.getcwd(), file=fp)
thanks!  I think there should indeed be a better way (see e.g. how we handle filtering out of progress indication log messages in datalad: https://github.com/datalad/datalad/blob/master/datalad/log.py#L262 ) but let's proceed.

2020-12-16 17:35 UTC, merged