Update upload code for new API
dandi/dandi-cli pull request #479
Opened 2021-03-19 18:41 UTC by jwodder

2021-03-19 22:42 UTC, yarikoptic requested changes
An initial quick review: I have not spotted anything "incorrect" but we should switch away from sha256 for upload/download; and fix those `uuid`s in variable names.

<details>
<summary>FWIW: initial upload attempt didn't succeed yet</summary> 

```shell
*$> DANDI_DEVEL=1 dandi upload -i dandi-api --validation=ignore sub-RAT123/sub-RAT123.nwb
2021-03-19 18:40:38,432 [    INFO] Found 1 files to consider
PATH                      SIZE       ERRORS     UPLOAD STATUS                MESSAGE
sub-RAT123/sub-RAT123.nwb 18.8 kB       1              ERROR                 Error 500 while sending PO...
Summary:                  18.8 kB 1 with errors        1 ERROR               1 Error 500 while sending ...
2021-03-19 18:40:39,719 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210319224036Z-7318.log
(dandi-devel) (git)/mnt/backup/dandi/dandisets/000027:[master]
#27 !1158 [0].....................................:Fri Mar 19 18:40:39:.
drogon:/mnt/backup/dandi/dandisets/000027
$> cat /home/yoh/.cache/dandi-cli/log/20210319224036Z-7318.log
2021-03-19T18:40:36-0400 [INFO    ] dandi 7318:140182937339264 [META] sys.argv = ['/home/yoh/miniconda3/envs/dandi-devel/bin/dandi', 'upload', '-i', 'dandi-api', '--validation=ignore', 'sub-RAT123/sub-RAT123.nwb']
2021-03-19T18:40:36-0400 [INFO    ] dandi 7318:140182937339264 [META] os.getcwd() = /mnt/backup/dandi/dandisets/000027
2021-03-19T18:40:38-0400 [INFO    ] dandi 7318:140182937339264 Found 1 files to consider
2021-03-19T18:40:38-0400 [ERROR   ] dandi 7318:140182342420224 Error 404 while sending POST request to https://api.dandiarchive.org/api/blobs/digest/: {"detail":"Not found."}
2021-03-19T18:40:39-0400 [ERROR   ] dandi 7318:140182342420224 Error 500 while sending POST request to https://api.dandiarchive.org/api/uploads/initialize/: 
<!doctype html>
<html lang="en">
<head>
  <title>Server Error (500)</title>
</head>
<body>
  <h1>Server Error (500)</h1><p></p>
</body>
</html>

2021-03-19T18:40:39-0400 [INFO    ] dandi 7318:140182937339264 Logs saved in /home/yoh/.cache/dandi-cli/log/20210319224036Z-7318.log

```
</details>

2021-03-19 22:42 UTC, yarikoptic commented on dandi/download.py
> +                        digests = {"sha256": d["value"]}
sha256 is not guaranteed to be available, `dandi-etag` should always be there... we could test using both if present and even announce us whenever we run into a collision of having one matching and another not, but I would for now just switch to use `dandi-etag` consistently throughout and forget about sha256 as long as we are dealing with new API

2021-03-22 13:33 UTC, jwodder commented on dandi/dandiapi.py
> +                asset_uuid = resp["uuid"]
@dchiquito Can/should requests to `PUT /dandisets/{versions__dandiset__pk}/versions/{versions__version}/assets/{uuid}/` be replaced by `POST /dandisets/{versions__dandiset__pk}/versions/{versions__version}/assets/`?

2021-03-22 13:35 UTC, jwodder commented on dandi/upload.py
> +                for d in metadata.get("digest", []):
This will require a `DigestType` value for ETags (cc: @satra).

2021-03-22 16:33 UTC, yarikoptic commented on dandi/upload.py
> +                for d in metadata.get("digest", []):
don't we have `cryptoType` already, see e.g. https://github.com/dandi/dandi-api-datasets/blob/master/000003/sub-YutaMouse20/sub-YutaMouse20_ses-YutaMouse20-140321_behavior%2Becephys.nwb.yaml#L7

2021-03-22 16:41 UTC, jwodder commented on dandi/upload.py
> +                for d in metadata.get("digest", []):
@yarikoptic That field is an enum, and the corresponding enum type currently does not have a value for ETags.

2021-03-22 16:48 UTC, yarikoptic commented on dandi/upload.py
> +                for d in metadata.get("digest", []):
Please add it within this PR or even better as a separate PR (with patch version increment for the schema)

2021-03-22 16:50 UTC, jwodder commented on dandi/upload.py
> +                for d in metadata.get("digest", []):
@yarikoptic The enum definitions involve metadata produced by @satra that I'm not sure how to extend (hence why I pinged him earlier).

2021-03-22 16:54 UTC, satra commented on dandi/upload.py
> +                for d in metadata.get("digest", []):
i would just suggest adding another entry to this: https://github.com/dandi/dandi-cli/blob/master/dandi/model_types.py#L59 

you can call it: `dandi:dandi-s3-etag`

2021-03-22 16:56 UTC, jwodder commented on dandi/upload.py
> +                for d in metadata.get("digest", []):
@satra Is that value for the `@id` field?  What should the other fields be?

2021-03-22 16:59 UTC, satra commented on dandi/upload.py
> +                for d in metadata.get("digest", []):
yes, type stays the same as the others. comment is a description, you can make it as brief or elaborate as you want it to be. label is a short name and "DANDI S3 Etag" should work just fine.

2021-03-22 16:59 UTC, yarikoptic commented on dandi/upload.py
> +                for d in metadata.get("digest", []):
> you can call it: dandi:dandi-s3-etag

Let's call it just `dandi-etag` (not dandi-s3-etag) though as was decided (somewhat) and implemented

2021-03-23 12:43 UTC, jwodder commented
@yarikoptic I added a test that uploads & downloads an empty file, but the upload fails with:

```
Error 400 while sending POST request to http://localhost:8000/api/uploads/initialize/: {"contentSize":["Ensure this value is greater than or equal to 1."]}
```

cc: @dchiquito

2021-03-23 13:08 UTC, yarikoptic commented
ok, filed a dedicated https://github.com/dandi/dandi-api/issues/168 .  So let's skip (comment out) such a test and proceed to length 1 ;)

2021-03-23 13:27 UTC, jwodder commented
@yarikoptic I'm now manually testing uploading a zero-byte file and a one-byte file to https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/000029.  The zero-byte file is failing for the reason above, and the upload of the one-byte file is failing on a 500 server error on the request to `/uploads/initialize/`.

2021-03-23 15:44 UTC, dchiquito commented
@jwodder It looks like AWS returned that bizarrely shaped key instead of a UUID. https://github.com/dandi/dandi-api/pull/170 should fix the issue.

2021-03-23 15:54 UTC, dchiquito commented on dandi/dandiapi.py
> +                asset_uuid = resp["uuid"]
No, you should still use `PUT`. In addition to creating the new `Asset`, it also unlinks the old asset, and links the new asset to the old asset. If you used `POST` to try to update metadata, the old asset with the old metadata would still be associated with the version.

2021-03-23 15:56 UTC, jwodder commented
@dchiquito Isn't the response to POSTing to the `complete_url` supposed to include an ETag header which the client is then supposed to compare against its computed ETag for the file?  Because that header isn't present when uploading to the new API.  (It's there when using minio for the Dockerized tests, though.)

2021-03-23 16:09 UTC, dchiquito commented
@jwodder the `complete_url` points directly to the objects store, so it's up to them how the response is shaped. The [S3 documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CompleteMultipartUpload.html#API_CompleteMultipartUpload_ResponseSyntax) says ETag is included in the response body (as XML :vomiting_face:), but not in the headers? I definitely see an `ETag` header when using Minio, but apparently that's not how S3 behaves. I'm surprised, I thought Minio was aiming for maximum S3 compliance.

2021-03-23 16:43 UTC, jwodder commented
@dchiquito After updating for that, uploads to the server are now failing with:

```
Error 400 while sending POST request to https://api.dandiarchive.org/api/uploads/045ddaa2-f932-428e-b8f6-b1c440264b3f/validate/: ["ETag does not match."]
```

The logs indicate the ETags do match, though.  Am I supposed to surround the ETag in double-quotes when submitting it to the server?  This error does not occur when testing against the Dockerized environment.

2021-03-23 17:03 UTC, dchiquito commented
@jwodder I agree everything matches. I'm adding some logging, though I suspect you are right and AWS is wrapping it in `""` for some reason.

2021-03-23 17:26 UTC, dchiquito commented
@jwodder just validated that upload through the API and it worked. It was indeed S3 returning double quotes. Everything should be hunky dory now.

2021-03-23 18:47 UTC, yarikoptic commented
woohoo -- green again!  @jwodder please "check" the boxes in the original issue description whenever those are addressed/done

2021-03-24 12:34 UTC, yarikoptic commented
<details>
<summary>Upload on 3TB file errored out for me with LooseVersion' object has no attribute 'version'</summary> 

```shell
drogon:/tmp/000029
*$> DANDI_DEVEL=1 dandi upload -i dandi-api --allow-any-path largeuploads/blobs/f5d/aac/79d9c6c1ba2439200d45680f1cb941087750a000e484ea2973232709d2
2021-03-23 19:03:10,248 [ WARNING] A newer version (0.12.0) of dandi/dandi-cli is available. You are using 0.11.0+52.g345866d
2021-03-23 19:03:11,770 [    INFO] Found 1 files to consider
PATH                                                                                  SIZE    ERRORS UPLOAD STATUS           MESSAGE
largeuploads/blobs/f5d/aac/79d9c6c1ba2439200d45680f1cb941087750a000e484ea2973232709d2 3.6 TB                ERROR            'LooseVersion' object has no attribute 'version'
Summary:                                                                              3.6 TB                1 ERROR          1 'LooseVersion' object has no attribute 'version'
2021-03-23 23:30:04,598 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210323230310Z-12419.log
(dandi-devel)
#52 !1183 [0].....................................:Tue Mar 23 23:30:04:.
drogon:/tmp/000029
$> cat /home/yoh/.cache/dandi-cli/log/20210323230310Z-12419.log
2021-03-23T19:03:10-0400 [INFO    ] dandi 12419:139962955457920 [META] sys.argv = ['/home/yoh/miniconda3/envs/dandi-devel/bin/dandi', 'upload', '-i', 'dandi-api', '--allow-any-path', 'largeuploads/blobs/f5d/aac/79
d9c6c1ba2439200d45680f1cb941087750a000e484ea2973232709d2']
2021-03-23T19:03:10-0400 [INFO    ] dandi 12419:139962955457920 [META] os.getcwd() = /tmp/000029
2021-03-23T19:03:10-0400 [WARNING ] dandi 12419:139962955457920 A newer version (0.12.0) of dandi/dandi-cli is available. You are using 0.11.0+52.g345866d
2021-03-23T19:03:11-0400 [INFO    ] dandi 12419:139962955457920 Found 1 files to consider
2021-03-23T23:30:04-0400 [INFO    ] dandi 12419:139962955457920 Logs saved in /home/yoh/.cache/dandi-cli/log/20210323230310Z-12419.log
(dandi-devel) 
#53 !1184 [0].....................................:Wed Mar 24 08:29:45:.
drogon:/tmp/000029
$> dandi --version
0.11.0+52.g345866d

```
</details>

2021-03-24 12:40 UTC, jwodder commented
@yarikoptic Could you rerun with `--devel-debug`?  I only see two locations in dandi that use `LooseVersion`, and neither accesses a `version` attribute.

2021-03-24 12:50 UTC, yarikoptic commented
```
*$> DANDI_DEVEL=1 dandi upload -i dandi-api --allow-any-path --devel-debug largeuploads/blobs/f5d/aac/79d9c6c1ba2439200d45680f1cb941087750a000e484ea2973232709d2 
2021-03-24 08:48:26,249 [ WARNING] A newer version (0.12.0) of dandi/dandi-cli is available. You are using 0.11.0+52.g345866d
2021-03-24 08:48:27,948 [    INFO] Found 1 files to consider
{'size': 3628888939868}
{'status': 'digesting'}
{'status': 'pre-validating'}
2021-03-24 08:48:28,326 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210324124825Z-15856.log
Traceback (most recent call last):
  File "/home/yoh/miniconda3/envs/dandi-devel/bin/dandi", line 33, in <module>
    sys.exit(load_entry_point('dandi', 'console_scripts', 'dandi')())
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/yoh/proj/dandi/dandi-cli/dandi/cli/base.py", line 109, in wrapper
    return f(*args, **kwargs)
  File "/home/yoh/proj/dandi/dandi-cli/dandi/cli/cmd_upload.py", line 98, in upload
    upload(
  File "/home/yoh/proj/dandi/dandi-cli/dandi/upload.py", line 49, in upload
    return _new_upload(
  File "/home/yoh/proj/dandi/dandi-cli/dandi/upload.py", line 897, in _new_upload
    for v in process_path(path, relpath):
  File "/home/yoh/proj/dandi/dandi-cli/dandi/upload.py", line 775, in process_path
    validation_errors = validate_file(path)
  File "/home/yoh/proj/dandi/dandi-cli/dandi/validate.py", line 41, in validate_file
    return pynwb_validate(filepath, devel_debug=devel_debug) + validate_dandi_nwb(
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/fscacher/cache.py", line 116, in fingerprinter
    ret = fingerprinted(path, *args, **kwargs_)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/joblib/memory.py", line 591, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/joblib/memory.py", line 534, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/joblib/memory.py", line 761, in call
    output = self.func(*args, **kwargs)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/fscacher/cache.py", line 84, in fingerprinted
    return f(path, *args, **kwargs)
  File "/home/yoh/proj/dandi/dandi-cli/dandi/pynwb_utils.py", line 268, in validate
    if loosever and loosever < "2.1.0":
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/distutils/version.py", line 335, in _cmp
    if self.version == other.version:
AttributeError: 'LooseVersion' object has no attribute 'version'
```
which is odd ... fscacher 0.1.0 and joblib 1.0.1

2021-03-24 12:53 UTC, yarikoptic commented
damn - I think I was running an outdated version of this PR (and I thought I had checked)... will hard reset and redo now

2021-03-24 12:57 UTC, jwodder commented
@yarikoptic I see the problem.  `get_nwb_version()` is returning `None` for the file, leading to an invalid `LooseVersion` instance.

2021-03-24 13:04 UTC, yarikoptic commented
THANKS! I will interrupt, update, redo

2021-03-24 16:53 UTC, yarikoptic commented
Since CI is happy and basic testing is happy and that huge upload would take awhile, let's take this PR from draft and merge?  This should make CI happy for PRs so we do miss us breaking anything unrelated

2021-03-24 16:59 UTC, yarikoptic approved these changes

2021-03-24 16:59 UTC, merged