Add "delete" command
dandi/dandi-cli pull request #509
Opened 2021-03-26 16:04 UTC by jwodder

Closes #501.

2021-03-26 16:23 UTC, jwodder commented
@yarikoptic I'm unclear on how to properly invoke pyout.  My current attempt seems to result in pyout not consuming the iterators of progress dicts, and thus nothing is getting deleted.  (It works with `--devel-debug`, though.)

2021-03-26 19:10 UTC, jwodder commented
@yarikoptic @dchiquito I'm writing tests for the `delete()` function, but when running the entire test suite, it keeps failing because Django is erroring out with "psycopg2.OperationalError: FATAL: sorry, too many clients already".  Putting various things in sessions doesn't help.

2021-03-26 22:06 UTC, yarikoptic commented
@jwodder - is that for an asset delete or a dandiset delete?  smells like an issue to file against `dandi-api` since doesn't feel like anything to fix in dandi-cli.

2021-03-26 22:07 UTC, yarikoptic commented
@jwodder also does it work when you try DELETE on the api.dandiarchive.org or specific to docker-compose instance?

2021-03-26 22:26 UTC, jwodder commented
@yarikoptic I've only tested asset deletions so far, but the error is actually coming later in the test suite, after the deletion tests run — specifically, at `test_new_upload_extant_bad_existing` or adjacent.

2021-03-26 23:45 UTC, jwodder commented
@yarikoptic I was able to get the tests to pass again by making most dandi-api tests use the same `Session` instance, but I'm not convinced we won't run into this problem again later.

2021-03-29 15:48 UTC, yarikoptic commented
@jwodder please try it on the live instance.  Can do on any dandiset really besides that monster https://gui-beta-dandiarchive-org.netlify.app/#/dandiset/010000 which I am still uploading

2021-03-29 15:50 UTC, jwodder commented
@yarikoptic Try what on the live instance, exactly?  I already tried deleting assets from the live instance, and it worked.

2021-03-29 16:59 UTC, yarikoptic commented
I meant to try deleting (lots of?) assets on the live instance to see if similar "too many clients already" message would emerge in the dandi-api logs.

2021-03-29 17:13 UTC, yarikoptic requested changes
Looks great, thank you @jwodder .  I left just minor wishlists, the primary of which is to add a test run with pyout so we do not miss/spill some obvious errors into user faces.

2021-03-29 17:13 UTC, yarikoptic commented on dandi/delete.py
> +    deleting_dandiset: bool = False
please add a comment on what is the role of this `bool`

2021-03-29 17:13 UTC, yarikoptic commented on dandi/delete.py
> +class Deleter:
please add a docstring describing the purpose for this class

2021-03-29 17:13 UTC, yarikoptic commented on dandi/delete.py
> +            raise ValueError("Cannot delete assets from published versions")
should we just rely on dandi-api to disallow such action and client to not care?  sorry if I forgot if we ran into some stumbling point on that or what -- if to keep, a comment should be added on why we need this client side logic

2021-03-29 17:13 UTC, yarikoptic commented on dandi/delete.py
> +        if instance.metadata_version == 0:
```suggestion
        if instance.girder:
```
to make it more explicit than some possible relationship between having metadata version and girder

2021-03-29 17:13 UTC, yarikoptic commented on dandi/delete.py
> +                    out(gen)
please add at least a basic smoke test run with pyout as a backend to ensure that  no gotchas with pyout rendering etc,so we do not miss some breakage

2021-03-29 17:39 UTC, jwodder commented
@yarikoptic Review comments addressed.

2021-03-29 18:18 UTC, jwodder commented
@yarikoptic I deleted all 1328 assets in Dandiset 000008 with a single command, and there were no errors.

2021-03-29 18:20 UTC, yarikoptic commented
Thank you @jwodder !

2021-03-29 18:21 UTC, merged