RF: attempt nwb metadata extraction only on .nwb, if fails -- warning
dandi/dandi-cli pull request #733
Opened 2021-07-22 22:45 UTC by yarikoptic

I think time to assume that all NWB files would have .nwb extension I think.

This PR is maintaining prior behavior of re-raising the exception if allow_any_path is
False.  Otherwise -- and regardless if allow_any_path is True or not (thus
would not re-raise for non .nwb files even if not allow_any_path) - provide default
metadata record.

For upload it should be fine AFAIK even with the change  of behavior since we first
use allow_any_path to select .nwb files.

Closes #730

2021-07-22 23:37 UTC, jwodder requested changes

2021-07-22 23:37 UTC, jwodder commented on dandi/metadata.py
> +        if not allow_any_path:
This needs to be indented one level.

2021-07-23 00:10 UTC, satra commented on dandi/metadata.py
> +        if not allow_any_path:
+1 to this. otherwise LGTM

2021-07-23 12:41 UTC, jwodder approved these changes

2021-07-23 13:15 UTC, merged