Add `embargo_status` to dandiset endpoint
dandi/dandi-cli pull request #855
Opened 2021-12-21 21:34 UTC by dchiquito

Added in https://github.com/dandi/dandi-api/pull/643

@jwodder should I merge this before or after I merge the change in dandi-api?

2021-12-21 23:38 UTC, jwodder commented on dandi/tests/test_dandiapi.py
> +        "embargo_status": anys.ANY_STR,
This isn't enough.  You also need to actually add the field definition to `RemoteDandiset` in `dandiapi.py`, in the manner of, e.g., [`contact_person`](https://github.com/dandi/dandi-cli/blob/b825018c8a2d36bf1f1b516a4959e753e979dcf0/dandi/dandiapi.py#L680-L683).

2021-12-21 23:38 UTC, jwodder requested changes
This isn't enough.  You also need to actually add the field definition to `RemoteDandiset` in `dandiapi.py`, in the manner of, e.g., [`contact_person`](https://github.com/dandi/dandi-cli/blob/b825018c8a2d36bf1f1b516a4959e753e979dcf0/dandi/dandiapi.py#L680-L683).

2021-12-21 23:39 UTC, jwodder commented
@dchiquito 

> should I merge this before or after I merge the change in dandi-api?

Merge dandi-api first so that we can properly test dandi-cli.

2022-01-05 14:33 UTC, yarikoptic commented
@dchiquito please have a look to fix up linting and let's see current state of tests

2022-01-06 17:40 UTC, dchiquito commented
@jwodder I'm not sure why the windows/mac tests would pass while ubuntu fails. Are there any fundamental differences between them?

2022-01-06 17:42 UTC, jwodder commented
@dchiquito The Ubuntu tests are the only ones that include the tests of the Dockerized API.

2022-01-06 17:51 UTC, dchiquito commented
@jwodder what triggers https://hub.docker.com/r/dandiarchive/dandiarchive-api to be updated? Perusing https://github.com/dandi/dandi-api/blob/master/.github/workflows/cli-integration.yml suggests pushes to master, but I'm not clear if that includes merges or not.
Once the docker hub is updated I believe these tests should pass.

2022-01-06 17:53 UTC, jwodder commented
@dchiquito The Docker Hub image should be updated whenever the master branch of the repo is updated, whether by a merge or a direct push.

2022-01-06 19:26 UTC, jwodder approved these changes

2022-01-06 19:26 UTC, merged